name: Update Version

on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Increment version
        id: increment-version
        run: |
          npm run ver-sync increment

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update version"
          git push

      #- name: Merge development -> staging
      #  uses: devmasx/merge-branch@master
      #  with:
      #    type: now
      #    from_branch: production
      #    target_branch: master
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
